// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvOGlaJ3GzuG84Y8kdTdVAPqMrn_8nU6s',
    appId: '1:21860733232:android:efa33a92d580f3fbe238f5',
    messagingSenderId: '21860733232',
    projectId: 'walkshare-dev-46242',
    storageBucket: 'walkshare-dev-46242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOaDdCMz5xweDkiPXUkh5JzLILvLiQOko',
    appId: '1:21860733232:ios:cc79d8ec8f10cccee238f5',
    messagingSenderId: '21860733232',
    projectId: 'walkshare-dev-46242',
    storageBucket: 'walkshare-dev-46242.appspot.com',
    androidClientId: '21860733232-jmag20mml25j782h9cfot8o4tin555vf.apps.googleusercontent.com',
    iosClientId: '21860733232-vacbqfupn3lsvivr73vjm3clf40p25k7.apps.googleusercontent.com',
    iosBundleId: 'net-urban-theory.walkshare',
  );
}
