name: iOS Build Config

on:
  workflow_dispatch:

# このワークフローを実行する際は、Podfile, Podfile.lock両方の削除が必要です。
jobs:
  build-config:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          java-version: "17.x"
          distribution: "oracle"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"

      - name: Flutter build config only
        run: |
          flutter clean
          pod repo update
          flutter pub get
          flutter build ios --config-only --no-codesign

      - name: cat Podfile
        run: |
          cd ios
          cat Podfile
          cat Podfile.lock

      - name: Store Podfile
        uses: actions/upload-artifact@v4
        with:
          name: Podfile
          path: |
            ios/Podfile
            ios/Podfile.lock
